# Generated by Django 4.2.27 on 2026-02-03 11:04

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autoridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('cargo', models.CharField(default='Presidente Comunal', max_length=100)),
                ('mensaje', ckeditor.fields.RichTextField(verbose_name='Mensaje de Bienvenida')),
                ('foto', models.ImageField(upload_to='autoridades/', verbose_name='Foto de Perfil')),
                ('firma', models.ImageField(blank=True, help_text='Subí una imagen de tu firma en formato PNG con fondo transparente.', null=True, upload_to='autoridades/firmas/', verbose_name='Firma (PNG Transparente)')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Autoridades',
            },
        ),
        migrations.CreateModel(
            name='CategoriaNovedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre de la Categoría')),
            ],
            options={
                'verbose_name': 'Categoría de Novedad',
                'verbose_name_plural': 'Categorías de Novedades',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('balance', 'Balance Contable'), ('ordenanza', 'Ordenanza / Resolución'), ('boletin', 'Boletín Oficial'), ('licitacion', 'Licitación'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('archivo', models.FileField(upload_to='transparencia/')),
                ('fecha_publicacion', models.DateField(default=django.utils.timezone.now)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Documento de Transparencia',
                'verbose_name_plural': 'Documentos de Transparencia',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contenido', ckeditor.fields.RichTextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='historias/')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('aprobado', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='InfoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('icono', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('red', 'Rojo'), ('blue', 'Azul'), ('green', 'Verde'), ('orange', 'Naranja'), ('purple', 'Violeta'), ('gray', 'Gris')], default='green', max_length=20)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tarjeta de Información',
                'verbose_name_plural': 'Tarjetas de Información (Info Útil)',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('infraestructura', 'Obras Públicas'), ('educacion', 'Educación'), ('deporte', 'Deportes'), ('salud', 'Salud y Ambiente'), ('otros', 'Otros')], default='infraestructura', max_length=20)),
                ('descripcion_corta', models.CharField(help_text='Resumen para la tarjeta', max_length=300)),
                ('imagen', models.ImageField(help_text='Imagen de portada', upload_to='obras/')),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True)),
                ('nombre_apellido', models.CharField(max_length=120)),
                ('dni', models.CharField(db_index=True, max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('barrio', models.CharField(blank=True, max_length=80)),
                ('direccion', models.CharField(blank=True, max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('tema', models.CharField(help_text='Ej: Alumbrado, Bacheo, Basura, Ruidos molestos...', max_length=100, verbose_name='Tema del Reclamo')),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('recibido', 'Recibido'), ('en_proceso', 'En proceso'), ('resuelto', 'Resuelto')], default='recibido', max_length=20)),
                ('prioridad', models.PositiveIntegerField(default=3)),
                ('nota_interna', models.TextField(blank=True)),
                ('respuesta_publica', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamos_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reclamo',
                'verbose_name_plural': 'Reclamos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Secretaría',
                'verbose_name_plural': 'Secretarías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Nombre del Área / Servicio')),
                ('tipo', models.CharField(choices=[('contacto', 'Área / Secretaría'), ('emergencia', 'Emergencia'), ('transporte', 'Transporte')], max_length=20)),
                ('icono', models.CharField(default='fa-solid fa-building', max_length=50)),
                ('encargado', models.CharField(blank=True, max_length=100, verbose_name='Encargado/a')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono / WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto')),
                ('horario', models.CharField(blank=True, max_length=100, verbose_name='Días y Horarios')),
                ('direccion', models.CharField(blank=True, max_length=150, verbose_name='Dirección Física')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción extra si hace falta')),
            ],
            options={
                'verbose_name': 'Contacto / Servicio',
                'verbose_name_plural': 'Contactos y Servicios',
            },
        ),
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('general', 'General'), ('obras', 'Obras y Servicios'), ('cultura', 'Cultura y Deporte'), ('atencion', 'Atención al Público'), ('seguridad', 'Seguridad')], default='general', max_length=20)),
                ('mensaje', models.TextField(verbose_name='Tu sugerencia')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Sugerencia Anónima',
                'verbose_name_plural': 'Buzón de Sugerencias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('icono', models.CharField(help_text='Clase FontAwesome', max_length=50)),
                ('descripcion_breve', models.CharField(max_length=150)),
                ('requisitos', models.TextField(blank=True, help_text='Lista de qué llevar')),
                ('horario_atencion', models.CharField(blank=True, max_length=100)),
                ('responsable', models.CharField(blank=True, max_length=100)),
                ('telefono_area', models.CharField(blank=True, max_length=50)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='tramites/', verbose_name='Formulario PDF')),
            ],
        ),
        migrations.CreateModel(
            name='ReclamoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='reclamos/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('reclamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.reclamo')),
            ],
            options={
                'ordering': ['orden', 'creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ReclamoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=20)),
                ('estado_nuevo', models.CharField(blank=True, max_length=20)),
                ('comentario_interno', models.TextField(blank=True)),
                ('comentario_publico', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reclamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.reclamo')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='reclamo',
            name='secretaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamos', to='core.secretaria'),
        ),
        migrations.CreateModel(
            name='ObraImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='obras/galeria/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.obra')),
            ],
            options={
                'verbose_name': 'Imagen de Galería',
                'verbose_name_plural': 'Galería de la Obra',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('bajada', models.CharField(blank=True, help_text='Opcional. Texto corto para la tarjeta.', max_length=300, null=True, verbose_name='Resumen breve')),
                ('contenido', ckeditor.fields.RichTextField(blank=True, help_text='Opcional. Texto completo si el usuario hace clic.', null=True, verbose_name='Desarrollo de la noticia')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='novedades/')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('destacada', models.BooleanField(default=False)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.categorianovedad', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Novedad / Gestión',
                'verbose_name_plural': 'Gestión al Día',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='InfoDato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('icono_item', models.CharField(default='fa-solid fa-check', max_length=50)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos', to='core.infocategoria')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
