# Generated by Django 4.2.27 on 2026-05-09 21:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('bajada', models.CharField(blank=True, max_length=260, verbose_name='Texto breve')),
                ('url', models.URLField(verbose_name='URL del video')),
                ('portada', models.ImageField(blank=True, null=True, upload_to='videos/', verbose_name='Portada')),
                ('categoria', models.CharField(choices=[('obras', 'Obras'), ('gestion', 'Gestión'), ('comunidad', 'Comunidad'), ('eventos', 'Eventos'), ('entrevistas', 'Entrevistas')], default='gestion', max_length=20)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('destacado', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['orden', '-fecha'],
            },
        ),
    ]
